#+TITLE:	Exercício 8.19 (Tardos)
#+AUTHOR:	Alice Duarte Scarpa, Bruno Lucian Costa
#+EMAIL:	alicescarpa@gmail.com, bruno.lucian.costa@gmail.com
#+DATE:		2015-06-23
#+OPTIONS: tex:t
#+OPTIONS: toc:nil
#+STARTUP: showall
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LaTeX_HEADER: \usemintedstyle{perldoc}
#+LaTeX_HEADER: \usepackage{tikz}
#+LaTeX_HEADER: \usetikzlibrary{decorations.markings}
#+LaTeX_HEADER: \tikzstyle{vertex}=[circle, draw, inner sep=0pt, minimum size=7pt]
#+LaTeX_HEADER: \newcommand{\vertex}{\node[vertex]}

* Enunciado

Um comboio de navios chega ao porto com um total de $n$ vasilhames
contendo tipos diferentes de materiais perigosos.
Na doca, estão $m$ caminhões, cada um com capacidade para até $k$
vasilhames.  Para cada um dos dois problemas, dê um algoritmo
polinomial ou prove NP-completude:


- Cada vasilhame só pode ser carregado com segurança em alguns
  dos caminhões. Existe como estocar os $n$ vasilhames nos $m$
  caminhões de modo que nenhum caminhão esteja sobrecarregado, e
  todo vasilhame esteja num caminhão que o comporta com segurança?
- Qualquer vasilhame pode ser colocado em qualquer caminhão,
  mas alguns pares de vasilhames não podem ficar juntos num mesmo
  caminhão. Existe como estocar os $n$ vasilhames nos $m$
  caminhões de modo que nenhum caminhão esteja sobrecarregado e
  que nenhum dos pares proibidos de vasilhames esteja no mesmo
  caminhão?
